const { properties } = require("../utils/config");
const { Helper } = require("../utils/helper");

class IntlTravelInsurancePage extends Helper{
    constructor(){
        super(__filename);
    }

    async clickOnBundledPlan(){
        await this.clickElement(await this.findElement('getTravel'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('pickFromOurStandardPlans'))
    }

    async clickOnUnbundledPlan(){
        await this.clickElement(await this.findElement('getTravel'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('unbundledPlan'))
    }

    async buy_journey_for_2_Adults_30_days_period_and_200K_SI(){
        await this.sleep(2)
        await this.clickElement(await this.findElement('wherePlaceholder'))
        await this.clickElement(await this.findElement('clickOnCountry1','United Kingdom'))
        await this.clickElement(await this.findElement('done'))
        await this.clickElement(await this.findElement('dateInput'))
        let currentDate = new Date()
        let nextMonthDate = new Date(currentDate.setMonth(currentDate.getMonth() + 1))
        let formattedDate = new Intl.DateTimeFormat('en-US', {month: 'long', year: 'numeric'}).format(nextMonthDate)
        await this.clickElement(await this.findElement('1stOfMonth',formattedDate))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('30thOfMonth',formattedDate))
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('denailAddOn'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('fullName',1))
        await this.sendKeys('Meet marakana')
        await this.clickElement(await this.findElement('dayOfDOB',1))
        await this.sendKeys('15')
        await this.clickElement(await this.findElement('monthOfDOB',1))
        await this.sendKeys('05')
        await this.clickElement(await this.findElement('yearOfDOB',1))
        await this.sendKeys('1997')
        await this.clickElement(await this.findElement('gender',1))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('pincode',1))
        await this.sendKeys('560037')
        await this.clickElement(await this.findElement('emailInput',1))
        await this.sendKeys('meet.marakana@acko.tech')
        await this.clickElement(await this.findElement('fullName',2))
        await this.sendKeys('Chandu champion')
        await this.clickElement(await this.findElement('dayOfDOB',2))
        await this.sendKeys('16')
        await this.clickElement(await this.findElement('monthOfDOB',2))
        await this.sendKeys('06')
        await this.clickElement(await this.findElement('yearOfDOB',2))
        await this.sendKeys('1998')
        await this.clickElement(await this.findElement('gender',2))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('continueCTA'))
    }

    async buy_journey_for_1_Adults_and_1_Senior_120_days_period_and_100K_SI(){
        await this.sleep(2)
        await this.clickElement(await this.findElement('wherePlaceholder'))
        await this.clickElement(await this.findElement('clickOnCountry1','United Kingdom'))
        await this.clickElement(await this.findElement('done'))
        await this.clickElement(await this.findElement('dateInput'))
        let currentDate = new Date();
        let nextMonthDate = new Date(currentDate.setMonth(currentDate.getMonth() + 1));
        let targetDate = new Date(nextMonthDate);
        let newTargetDate =  targetDate.setMonth(targetDate.getMonth() + 4);
        let startFormattedDate = new Intl.DateTimeFormat('en-US', {month: 'long', year: 'numeric'}).format(nextMonthDate)
        let endFormattedDate = new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(newTargetDate);
        await this.clickElement(await this.findElement('1stOfMonth',startFormattedDate))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('1stOfMonth',endFormattedDate))
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('addTravellerCount','Senior citizen'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('priceSet'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('denailAddOn'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('fullName',1))
        await this.sendKeys('Meet marakana')
        await this.clickElement(await this.findElement('dayOfDOB',1))
        await this.sendKeys('15')
        await this.clickElement(await this.findElement('monthOfDOB',1))
        await this.sendKeys('05')
        await this.clickElement(await this.findElement('yearOfDOB',1))
        await this.sendKeys('1997')
        await this.clickElement(await this.findElement('gender',1))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('pincode',1))
        await this.sendKeys('560037')
        await this.clickElement(await this.findElement('emailInput',1))
        await this.sendKeys('meet.marakana@acko.tech')
        await this.clickElement(await this.findElement('fullName',2))
        await this.sendKeys('Chandu champion')
        await this.clickElement(await this.findElement('dayOfDOB',2))
        await this.sendKeys('16')
        await this.clickElement(await this.findElement('monthOfDOB',2))
        await this.sendKeys('06')
        await this.clickElement(await this.findElement('yearOfDOB',2))
        await this.sendKeys('1998')
        await this.clickElement(await this.findElement('gender',2))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('continueCTA'))
        await this.clickElement(await this.findElement('specializedContinue'))
    }

    async buy_journey_for_1_Adults_and_1_Child_10_days_period_and_50K_SI(){
        await this.sleep(2)
        await this.clickElement(await this.findElement('wherePlaceholder'))
        await this.clickElement(await this.findElement('clickOnCountry1','Indonesia'))
        await this.clickElement(await this.findElement('done'))
        await this.clickElement(await this.findElement('dateInput'))
        let currentDate = new Date()
        let nextMonthDate = new Date(currentDate.setMonth(currentDate.getMonth() + 1))
        let formattedDate = new Intl.DateTimeFormat('en-US', {month: 'long', year: 'numeric'}).format(nextMonthDate)
        await this.clickElement(await this.findElement('1stOfMonth',formattedDate))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('10thOfMonth',formattedDate))
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('addTravellerCount','Child'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('priceSetLower'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA')) 
        await this.sleep(3)
        await this.clickElement(await this.findElement('denailAddOn'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('fullName',1))
        await this.sendKeys('Meet marakana')
        await this.clickElement(await this.findElement('dayOfDOB',1))
        await this.sendKeys('15')
        await this.clickElement(await this.findElement('monthOfDOB',1))
        await this.sendKeys('05')
        await this.clickElement(await this.findElement('yearOfDOB',1))
        await this.sendKeys('1997')
        await this.clickElement(await this.findElement('gender',1))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('pincode',1))
        await this.sendKeys('560037')
        await this.clickElement(await this.findElement('emailInput',1))
        await this.sendKeys('meet.marakana@acko.tech')
        await this.clickElement(await this.findElement('fullName',2))
        await this.sendKeys('Chandu champion')
        await this.clickElement(await this.findElement('dayOfDOB',2))
        await this.sendKeys('16')
        await this.clickElement(await this.findElement('monthOfDOB',2))
        await this.sendKeys('06')
        await this.clickElement(await this.findElement('yearOfDOB',2))
        await this.sendKeys('1998')
        await this.clickElement(await this.findElement('gender',2))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('continueCTA'))
        await this.clickElement(await this.findElement('specializedContinue'))
    }

    async buy_journey_for_2_Adults_10_days_period_100K_SI_only_medical_cover(){
        await this.sleep(2)
        await this.clickElement(await this.findElement('wherePlaceholder'))
        await this.clickElement(await this.findElement('clickOnCountry1','Indonesia'))
        await this.clickElement(await this.findElement('done'))
        await this.clickElement(await this.findElement('dateInput'))
        let currentDate = new Date()
        let nextMonthDate = new Date(currentDate.setMonth(currentDate.getMonth() + 1))
        let formattedDate = new Intl.DateTimeFormat('en-US', {month: 'long', year: 'numeric'}).format(nextMonthDate)
        await this.clickElement(await this.findElement('1stOfMonth',formattedDate))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('10thOfMonth',formattedDate))
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('addFor',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('skip'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('noThanks',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('noThanks',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('fullName',1))
        await this.sendKeys('Meet marakana')
        await this.clickElement(await this.findElement('dayOfDOB',1))
        await this.sendKeys('15')
        await this.clickElement(await this.findElement('monthOfDOB',1))
        await this.sendKeys('05')
        await this.clickElement(await this.findElement('yearOfDOB',1))
        await this.sendKeys('1997')
        await this.clickElement(await this.findElement('gender',1))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('pincode',1))
        await this.sendKeys('560037')
        await this.clickElement(await this.findElement('emailInput',1))
        await this.sendKeys('meet.marakana@acko.tech')
        await this.clickElement(await this.findElement('fullName',2))
        await this.sendKeys('Chandu champion')
        await this.clickElement(await this.findElement('dayOfDOB',2))
        await this.sendKeys('16')
        await this.clickElement(await this.findElement('monthOfDOB',2))
        await this.sendKeys('06')
        await this.clickElement(await this.findElement('yearOfDOB',2))
        await this.sendKeys('1998')
        await this.clickElement(await this.findElement('gender',2))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('continueCTA'))
    }

    async buy_journey_for_2_Adults_10_days_period_4hrs_only_flight_cover(){
        await this.sleep(2)
        await this.clickElement(await this.findElement('wherePlaceholder'))
        await this.clickElement(await this.findElement('clickOnCountry1','Indonesia'))
        await this.clickElement(await this.findElement('done'))
        await this.clickElement(await this.findElement('dateInput'))
        let currentDate = new Date()
        let nextMonthDate = new Date(currentDate.setMonth(currentDate.getMonth() + 1))
        let formattedDate = new Intl.DateTimeFormat('en-US', {month: 'long', year: 'numeric'}).format(nextMonthDate)
        await this.clickElement(await this.findElement('1stOfMonth',formattedDate))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('10thOfMonth',formattedDate))
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('noThanks',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('noThanks',2))
        await this.sleep(2)
        await this.clickElement(await this.findElement('4hours'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('addFor',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('noThanks',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('fullName',1))
        await this.sendKeys('Meet marakana')
        await this.clickElement(await this.findElement('dayOfDOB',1))
        await this.sendKeys('15')
        await this.clickElement(await this.findElement('monthOfDOB',1))
        await this.sendKeys('05')
        await this.clickElement(await this.findElement('yearOfDOB',1))
        await this.sendKeys('1997')
        await this.clickElement(await this.findElement('gender',1))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('pincode',1))
        await this.sendKeys('560037')
        await this.clickElement(await this.findElement('emailInput',1))
        await this.sendKeys('meet.marakana@acko.tech')
        await this.clickElement(await this.findElement('fullName',2))
        await this.sendKeys('Chandu champion')
        await this.clickElement(await this.findElement('dayOfDOB',2))
        await this.sendKeys('16')
        await this.clickElement(await this.findElement('monthOfDOB',2))
        await this.sendKeys('06')
        await this.clickElement(await this.findElement('yearOfDOB',2))
        await this.sendKeys('1998')
        await this.clickElement(await this.findElement('gender',2))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('continueCTA'))
    }

    async buy_journey_for_2_Adults_10_days_period_and_only_baggage_cover(){
        await this.sleep(2)
        await this.clickElement(await this.findElement('wherePlaceholder'))
        await this.clickElement(await this.findElement('clickOnCountry1','Indonesia'))
        await this.clickElement(await this.findElement('done'))
        await this.clickElement(await this.findElement('dateInput'))
        let currentDate = new Date()
        let nextMonthDate = new Date(currentDate.setMonth(currentDate.getMonth() + 1))
        let formattedDate = new Intl.DateTimeFormat('en-US', {month: 'long', year: 'numeric'}).format(nextMonthDate)
        await this.clickElement(await this.findElement('1stOfMonth',formattedDate))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('10thOfMonth',formattedDate))
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('noThanks',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('noThanks',2))
        await this.sleep(2)
        await this.clickElement(await this.findElement('noThanks',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('addFor',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('fullName',1))
        await this.sendKeys('Meet marakana')
        await this.clickElement(await this.findElement('dayOfDOB',1))
        await this.sendKeys('15')
        await this.clickElement(await this.findElement('monthOfDOB',1))
        await this.sendKeys('05')
        await this.clickElement(await this.findElement('yearOfDOB',1))
        await this.sendKeys('1997')
        await this.clickElement(await this.findElement('gender',1))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('pincode',1))
        await this.sendKeys('560037')
        await this.clickElement(await this.findElement('emailInput',1))
        await this.sendKeys('meet.marakana@acko.tech')
        await this.clickElement(await this.findElement('fullName',2))
        await this.sendKeys('Chandu champion')
        await this.clickElement(await this.findElement('dayOfDOB',2))
        await this.sendKeys('16')
        await this.clickElement(await this.findElement('monthOfDOB',2))
        await this.sendKeys('06')
        await this.clickElement(await this.findElement('yearOfDOB',2))
        await this.sendKeys('1998')
        await this.clickElement(await this.findElement('gender',2))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('continueCTA'))
    }

    async buy_journey_for_2_Adults_10_days_period_100K_SI_4hrs_and_all_covers(){
        await this.sleep(2)
        await this.clickElement(await this.findElement('wherePlaceholder'))
        await this.clickElement(await this.findElement('clickOnCountry1','Indonesia'))
        await this.clickElement(await this.findElement('done'))
        await this.clickElement(await this.findElement('dateInput'))
        let currentDate = new Date()
        let nextMonthDate = new Date(currentDate.setMonth(currentDate.getMonth() + 1))
        let formattedDate = new Intl.DateTimeFormat('en-US', {month: 'long', year: 'numeric'}).format(nextMonthDate)
        await this.clickElement(await this.findElement('1stOfMonth',formattedDate))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('10thOfMonth',formattedDate))
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(0.5)
        await this.clickElement(await this.findElement('addTravellerCount','Adult'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(3)
        await this.clickElement(await this.findElement('continueCTA'))
        await this.sleep(2)
        await this.clickElement(await this.findElement('addFor',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('addFor',2))
        await this.sleep(2)
        await this.clickElement(await this.findElement('addFor',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('addFor',1))
        await this.sleep(2)
        await this.clickElement(await this.findElement('fullName',1))
        await this.sendKeys('Meet marakana')
        await this.clickElement(await this.findElement('dayOfDOB',1))
        await this.sendKeys('15')
        await this.clickElement(await this.findElement('monthOfDOB',1))
        await this.sendKeys('05')
        await this.clickElement(await this.findElement('yearOfDOB',1))
        await this.sendKeys('1997')
        await this.clickElement(await this.findElement('gender',1))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('pincode',1))
        await this.sendKeys('560037')
        await this.clickElement(await this.findElement('emailInput',1))
        await this.sendKeys('meet.marakana@acko.tech')
        await this.clickElement(await this.findElement('fullName',2))
        await this.sendKeys('Chandu champion')
        await this.clickElement(await this.findElement('dayOfDOB',2))
        await this.sendKeys('16')
        await this.clickElement(await this.findElement('monthOfDOB',2))
        await this.sendKeys('06')
        await this.clickElement(await this.findElement('yearOfDOB',2))
        await this.sendKeys('1998')
        await this.clickElement(await this.findElement('gender',2))
        await this.clickElement(await this.findElement('selectGender','Male'))
        await this.clickElement(await this.findElement('continueCTA'))
    }

    async paymentProcess(){
        await this.sleep(2)
        await this.clickElement(await this.findElement('paySecurely'))
    }
}

module.exports = IntlTravelInsurancePage;